// <auto-generated />
using Cityinfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cityinfo.API.Migrations
{
    [DbContext(typeof(ProvinceInfoContext))]
    [Migration("20230108201918_NewData1")]
    partial class NewData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Cityinfo.API.Entities.CitiesInProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("CitiesInProvinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".....",
                            Name = "Alibunar",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = ".....",
                            Name = "Bela Crkva",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = ".....",
                            Name = "Kanjiza",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = ".....",
                            Name = "Senta",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = ".....",
                            Name = "Majdanpek",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = ".....",
                            Name = "Donji Milanovac",
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("Cityinfo.API.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Severnobački okrug se nalazi na severu Republike Srbije. Ima 186.906 stanovnika (Popis iz 2011), a sedište okruga je u gradu Subotici.....",
                            Name = "Severnobački okrug"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Srednjobanatski upravni okrug se nalazi u severoistočnom delu Srbije. Ima ukupno 187.667 stanovnika (popis iz 2011). Prema preliminarnim podacima popisa 2022. okrug ima 159.030 stanovnika. Sedište okruga je u gradu Zrenjaninu.\n.....",
                            Name = "Srednjobanatski okrug"
                        },
                        new
                        {
                            Id = 3,
                            Description = ".....",
                            Name = "Severnobanatski okrug"
                        },
                        new
                        {
                            Id = 4,
                            Description = ".....",
                            Name = "Južnobanatski okrug"
                        },
                        new
                        {
                            Id = 5,
                            Description = ".....",
                            Name = "Zapadnobački okrug"
                        },
                        new
                        {
                            Id = 6,
                            Description = "....",
                            Name = "Sremski okrug"
                        },
                        new
                        {
                            Id = 7,
                            Description = ".....",
                            Name = "Južnobački okrug"
                        },
                        new
                        {
                            Id = 8,
                            Description = ".....",
                            Name = "Mačvanski okrug"
                        },
                        new
                        {
                            Id = 9,
                            Description = ".....",
                            Name = "Kolubarski okrug"
                        },
                        new
                        {
                            Id = 10,
                            Description = ".....",
                            Name = "Podunavski okrug"
                        },
                        new
                        {
                            Id = 11,
                            Description = "....",
                            Name = "Braničevski okrug"
                        },
                        new
                        {
                            Id = 12,
                            Description = ".....",
                            Name = "Šumadijski okrug"
                        },
                        new
                        {
                            Id = 13,
                            Description = ".....",
                            Name = "Pomoravski okrug"
                        },
                        new
                        {
                            Id = 14,
                            Description = ".....",
                            Name = "Borski okrug"
                        },
                        new
                        {
                            Id = 15,
                            Description = ".....",
                            Name = "Zaječarski okrug"
                        },
                        new
                        {
                            Id = 16,
                            Description = "....",
                            Name = "Zlatiborski okrug\n\n"
                        },
                        new
                        {
                            Id = 17,
                            Description = ".....",
                            Name = "Moravički okrug"
                        },
                        new
                        {
                            Id = 18,
                            Description = ".....",
                            Name = "Raški okrug"
                        },
                        new
                        {
                            Id = 19,
                            Description = ".....",
                            Name = "Rasinski okrug"
                        },
                        new
                        {
                            Id = 20,
                            Description = "IDEMO NIIIIIŠ.....",
                            Name = "Nišavski okrug"
                        },
                        new
                        {
                            Id = 21,
                            Description = "....",
                            Name = "Toplički okrug"
                        },
                        new
                        {
                            Id = 22,
                            Description = ".....",
                            Name = "Pirotski okrug"
                        },
                        new
                        {
                            Id = 23,
                            Description = ".....",
                            Name = "Jablanički okrug"
                        },
                        new
                        {
                            Id = 24,
                            Description = ".....",
                            Name = "Pčinjski okrug"
                        },
                        new
                        {
                            Id = 25,
                            Description = ".....",
                            Name = "Kosovski okrug"
                        },
                        new
                        {
                            Id = 26,
                            Description = "....",
                            Name = "Pećki okrug"
                        },
                        new
                        {
                            Id = 27,
                            Description = ".....",
                            Name = "Prizrenski okrug"
                        },
                        new
                        {
                            Id = 28,
                            Description = ".....",
                            Name = "Kosovsko-mitrovački okrug"
                        },
                        new
                        {
                            Id = 29,
                            Description = ".....",
                            Name = "Kosovsko-pomoravski okrug"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Beograd, Beograd\ntri puta, po naški je.....",
                            Name = "Beograd"
                        });
                });

            modelBuilder.Entity("Cityinfo.API.Entities.CitiesInProvince", b =>
                {
                    b.HasOne("Cityinfo.API.Entities.Province", "Province")
                        .WithMany("CitiesInProvince")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Cityinfo.API.Entities.Province", b =>
                {
                    b.Navigation("CitiesInProvince");
                });
#pragma warning restore 612, 618
        }
    }
}
